### ISSUE TITLE
Shortcut doesn't work in Godot 4 beta 4

### ISSUE THREAD

**Issue by krazyjakee** [Kubulambula/Godot-GDShell#1]
After installing and enabling the plugin, the keyboard shortcut isn't created and when created manually, the console doesn't show.

Additionally, if I manually add a GDShellMain Node, it appears permanently and never disappears or reacts to the keyboard shortcut.

**Comment by Kubulambula** [comment]
Did you install the plugin via Asset Library?

The version on in the Asset Lib, that installs itself is outdated and I will update it this week so it is up to date.
If you want the latest version, just download the master branch and place it manually in the `addons/` folder.

**Comment by krazyjakee** [comment]
Thanks!
