### ISSUE TITLE
Move relevant constants to ProjectSettings 

### ISSUE THREAD

**Issue by auralluring** [Kubulambula/Godot-GDShell#16]
Hi, I really like this plugin. I want to use it in my game, but I also want to heavily customize it. Currently it seems in order to do that, I have to edit the scripts themselves. This is not ideal, since that means potential merge conflicts every time I update it.

I propose that some constants are moved to the ProjectSettings, such as the command file directory and the ui handler scene.

I will very likely end up making my own small modifications to the scripts actual behaviour-wise, but I still want to minimize them.

**Comment by Kubulambula** [comment]
That would make sense as GDShell already uses input maps to toggle the UI and it could be still modifiable trough code.
