### ISSUE TITLE
No list of commands

### ISSUE THREAD

**Issue by tryoxiss** [Kubulambula/Godot-GDShell#4]
There isn't a docs article with a comprehsnvie list of commands, or proper syntax. Each of the commands has a basic `man` article in its script, but thats not super clear docs wise.

**Comment by Kubulambula** [comment]
The docs are very unclear indeed, and not just in this area.
It would be great to have docs for every command beyond their `man` page.

Also all the commands could be listed via the `man` command itself.
Having options like `man --list` and `man -l` could be a great addidion.

**Comment by tryoxiss** [comment]
Because list isn't likely a commonly used flag I think `-L` would be better but `--list` would be good yeah.

**Comment by Kubulambula** [comment]
I quickly added the list option.

It showed me that it would be best if the rework of `GDShellCommandParser` and `GDShelCommandRunner`, would include the `GDShellCommandDB` because the way of handling aliases is really awkward.
